esphome:
  name: esp32-poe-technik
  friendly_name: ESP32-PoE Technik
  platformio_options:
    build_flags:
      - "-std=gnu++17"
    build_unflags:
      - "-std=gnu++11"
      - "-fno-rtti"

esp32:
  board: esp32-poe
  framework:
    type: arduino

# Enable logging
logger:
  level: INFO
  baud_rate: 0
  hardware_uart: UART1

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

ota:
  platform: esphome
  password: !secret ota_password

time:
  - platform: homeassistant
    id: homeassistant_time

substitutions:
  interval_very_fast: 15s
  interval_fast: 30s
  interval_medium: 60s
  interval_slow: 5min
  interval_very_slow: 15min
  interval_once_in_a_while: 1h

button:
  - platform: restart
    name: "Restart ESP32-PoE Technik"
#########################################
#                                       #
#   ETHERNET Konfiguration              #
#                                       #
#########################################
ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO0_OUT
  phy_addr: 0
  power_pin: GPIO12

#########################################
#                                       #
#   Packages                            #
#                                       #
#########################################
packages:
  energymeter: !include yaml/energymeter.yaml
  watermeter: !include yaml/watermeter.yaml
  sensors: !include yaml/sensors.yaml
  thz504: !include yaml/thz504.yaml
  kondensatpumpe: !include yaml/kondensatpumpe.yaml
