defaults:
  exposed: "true"

binary_sensor:
  - platform: template
    name: ${name}
    id: ${name}
    trigger_on_initial_state: false
    on_state:
      then:
        - if:
            condition:
              lambda: 'return getWhitelistedEntities().contains(id(${name}));'
            then:
              - script.execute:
                  id: mqtt_push_event
                  suffix: ${name}
                  payload: !lambda 'return x ? "On" : "Off";'

esphome:
  on_boot:
    priority: 100.0 # AFTER_CONNECTION
    then:
      - lambda: |-
          if(${exposed}) {
            getWhitelistedEntities().insert(id(${name}));
          }
