binary_sensor:
  - platform: template
    name: ${name}
    id: ${name}
    trigger_on_initial_state: false
    on_state:
      then:
        - script.execute:
            id: mqtt_push_event
            suffix: ${name}
            payload: !lambda 'return x ? "ON" : "OFF";'
