defaults:
  icon: "mdi:blank"
  accuracy_decimals: "0"
  target: "Kessel"
  update_interval: "never"
  unit: ""
  scaler: "1.0"
  name_suffix: ""
  exposed: "true"

sensor:
  - platform: template
    name: ${property}${name_suffix}
    id: ${property}${name_suffix}
    icon: ${icon}
    unit_of_measurement: ${unit}
    accuracy_decimals: ${accuracy_decimals}
    update_interval: ${update_interval}
    state_class: "measurement"
    lambda: |-
        queueRequest(${target}, Property::k${property});
        return {};

esphome:
  on_boot:
    priority: 110.0 # AFTER_CONNECTION
    then:
      - lambda: |-
          CallbackHandler::instance().addCallback(std::make_pair(${target},Property::k${property}),[](const SimpleVariant& value){
              const auto newValue{${scaler} * value.get<float>()};
              auto property{id(${property}${name_suffix})};
              if(!std::is_eq(property->state <=> newValue)) {
                property->publish_state(newValue);
              }
          });
          queueRequest(${target}, Property::k${property});

          #if defined(ANALYTICS)
            if(${exposed}) {
              getWhitelistedEntities().insert(id(${property}${name_suffix}));
            }
          #endif
