defaults:
  target: "Kessel"
  name_suffix: ""
  exposed: "true"
  initial_option: "Unbekannt"

select:
  - platform: template
    name: ${property}
    id: ${property}
    options: ${options}
    initial_option: "${initial_option}"
    optimistic: true
    setup_priority: 100
    set_action:
      then:
        - lambda: |-
            const auto id_val = Mapper::instance().${mapper_func_set}(x);
            if(id_val.has_value()) {
              queueTransmission(CanNode::${target}, Property::k${property}, id_val.value());
            }
    on_value:
      then:
        - if:
            condition:
              lambda: |-
                #if defined(ANALYTICS)
                  return getWhitelistedEntities().contains(id(${property}));
                #else
                  return false;
                #endif
            then:
              - script.execute:
                  id: mqtt_push_event
                  suffix: ${property}
                  payload: !lambda 'return x.c_str();'

esphome:
  on_boot:
    - priority: -50
      then:
        - lambda: |-
            CallbackHandler::instance().addCallback({CanNode::${target}, Property::k${property}}, [](const SimpleVariant& value) {
              const auto stringValue{value.get<std::string>()};
              const auto index = id(${property}).index_of(stringValue);
              if(index.has_value() && id(${property}).active_index() != index.value()) {
                id(${property}).publish_state(stringValue);
              }
            });

            #if defined(ANALYTICS)
              if(${exposed}) {
                getWhitelistedEntities().insert(id(${property}));
              }
            #endif
    - priority: -100.0
      then:
        - delay: 250ms
        - lambda: |-
            scheduleRequest(CanNode::${target}, Property::k${property}, std::chrono::seconds(10));
