defaults:
  target: "Kessel"
  icon: "mdi:toggle-switch-variant"
  exposed: "true"

switch:
  - platform: template
    name: ${property}
    id: ${property}
    icon: ${icon}
    restore_mode: DISABLED
    turn_on_action:
      - lambda: |-
          queueTransmission(${target}, Property::k${property}, static_cast<std::uint16_t>(true));
    turn_off_action:
      - lambda: |-
          queueTransmission(${target}, Property::k${property}, static_cast<std::uint16_t>(false));
    on_state:
      then:
        - if:
            condition:
              lambda: 'return getWhitelistedEntities().contains(id(${property}));'
            then:
              - script.execute:
                  id: mqtt_push_event
                  suffix: ${property}
                  payload: !lambda 'return x ? "On" : "Off";'

esphome:
  on_boot:
    priority: 100.0 # AFTER_CONNECTION
    then:
      - lambda: |-
          static_assert(Property::k${property}.type == Type::et_bool, "Only properties of type bool are supported by wp_switch.");

          CallbackHandler::instance().addCallbacks({std::make_pair(${target},Property::k${property}),
                                                    std::make_pair(Manager,Property::k${property})}, [](const SimpleVariant& value){
              id(${property}).publish_state(value);
          });
          queueRequest(${target}, Property::k${property});

          if(${exposed}) {
            getWhitelistedEntities().insert(id(${property}));
          }
