#if !defined(PROPERTY_H)
#define PROPERTY_H

#include <cstdint>
#include <sstream>
#include <string>
#include <unordered_map>
#include "type.h"

namespace oe32trta {
namespace detail {
struct Property {
    std::string_view name;
    std::uint16_t id{0U};
    Type type{Type::et_default};

    constexpr Property(const std::string_view _name, const std::uint16_t _id, const Type _type)
        : name(_name), id(_id), type(_type) {}
    constexpr Property(const std::string_view _name, const std::uint16_t _id) : name(_name), id(_id) {}

    constexpr operator std::uint16_t() const { return id; }

    Property& operator=(const Property& p) {
        name = p.name;
        id = p.id;
        type = p.type;
        return *this;
    }

   protected:
    Property getProperty(const std::uint16_t id);
};

class Mapper {
   public:
    Mapper() = default;
    inline Mapper(const Property& other) { map.insert({other.id, other}); }

    Property getProperty(const std::uint16_t id);

   private:
    static inline std::unordered_map<std::uint16_t, Property> map;
};

}  // namespace detail
}  // namespace oe32trta

#define PROPERTY(NAME, VALUE, ...)                                                    \
    static constexpr oe32trta::detail::Property k##NAME{#NAME, VALUE, ##__VA_ARGS__}; \
    static constexpr bool unique##VALUE{true};                                        \
    static inline oe32trta::detail::Mapper k##NAME##_MAPPING {                        \
        k##NAME                                                                       \
    }

struct Property : public oe32trta::detail::Property {
    constexpr Property(const Property& p) : oe32trta::detail::Property{p.name, p.id, p.type} {}
    constexpr Property(const oe32trta::detail::Property& p) : oe32trta::detail::Property{p.name, p.id, p.type} {}
    Property(const std::uint16_t _id) : oe32trta::detail::Property{getProperty(_id)} {}

    PROPERTY(INDEX_NOT_FOUND, 0x0000);
    PROPERTY(FEHLERMELDUNG, 0x0001);
    PROPERTY(SPEICHERSOLLTEMP, 0x0003, Type::et_dec_val);
    PROPERTY(VORLAUFSOLLTEMP, 0x0004, Type::et_dec_val);
    PROPERTY(AUSSENTEMP, 0x000c, Type::et_dec_val);
    PROPERTY(SPEICHERISTTEMP, 0x000e, Type::et_dec_val);
    PROPERTY(VERSTELLTE_RAUMSOLLTEMP, 0x0012, Type::et_dec_val);
    PROPERTY(STEIGUNG_HK1, 0x010e, Type::et_cent_val);
    PROPERTY(WOCHENTAG, 0x0121, Type::et_little_endian);
    PROPERTY(TAG, 0x0122, Type::et_little_endian);
    PROPERTY(MONAT, 0x0123, Type::et_little_endian);
    PROPERTY(JAHR, 0x0124, Type::et_little_endian);
    PROPERTY(STUNDE, 0x0125, Type::et_little_endian);
    PROPERTY(MINUTE, 0x0126, Type::et_little_endian);
    PROPERTY(SEKUNDE, 0x0127, Type::et_little_endian);
    PROPERTY(HEISSGAS_TEMP, 0x0265, Type::et_dec_val);
    PROPERTY(ANTEIL_VORLAUF_HK1, 0x059d);
    PROPERTY(FUSSPUNKT_HK1, 0x059e, Type::et_dec_val);
    PROPERTY(EL_ENERGIEAUFNAHME_WW_TAG_WH, 0x091a);
    PROPERTY(EL_ENERGIEAUFNAHME_WW_TAG_KWH, 0x091b, Type::et_double_val);
    PROPERTY(EL_ENERGIEAUFNAHME_WW_SUM_KWH, 0x091c);
    PROPERTY(EL_ENERGIEAUFNAHME_WW_SUM_MWH, 0x091d, Type::et_double_val);
    PROPERTY(EL_ENERGIEAUFNAHME_HEIZ_TAG_WH, 0x091e);
    PROPERTY(EL_ENERGIEAUFNAHME_HEIZ_TAG_KWH, 0x091f, Type::et_double_val);
    PROPERTY(EL_ENERGIEAUFNAHME_HEIZ_SUM_KWH, 0x0920);
    PROPERTY(EL_ENERGIEAUFNAHME_HEIZ_SUM_MWH, 0x0921, Type::et_double_val);
    PROPERTY(WAERMEERTRAG_WW_TAG_WH, 0x092a);
    PROPERTY(WAERMEERTRAG_WW_TAG_KWH, 0x092b, Type::et_double_val);
    PROPERTY(WAERMEERTRAG_WW_SUM_KWH, 0x092c);
    PROPERTY(WAERMEERTRAG_WW_SUM_MWH, 0x092d, Type::et_double_val);
    PROPERTY(WAERMEERTRAG_HEIZ_TAG_WH, 0x092e);
    PROPERTY(WAERMEERTRAG_HEIZ_TAG_KWH, 0x092f, Type::et_double_val);
    PROPERTY(WAERMEERTRAG_HEIZ_SUM_KWH, 0x0930);
    PROPERTY(WAERMEERTRAG_HEIZ_SUM_MWH, 0x0931, Type::et_double_val);

#if defined(THZ_504) || defined(THZ_404) || defined(THZ_5_5_ECO) || defined(TTF_07_C)
    PROPERTY(RAUMISTTEMP, 0x0011, Type::et_dec_val);
    PROPERTY(VERDAMPFERTEMP, 0x0014, Type::et_dec_val);
    PROPERTY(RUECKLAUFISTTEMP, 0x0016, Type::et_dec_val);
    PROPERTY(RAUMFEUCHTE, 0x0075, Type::et_dec_val);
    PROPERTY(RAUMEINFLUSS, 0x010f, Type::et_little_endian);
    PROPERTY(PROGRAMMSCHALTER, 0x0112, Type::et_betriebsart);
#endif

#if defined(THZ_504) || defined(THZ_404) || defined(THZ_5_5_ECO)
    PROPERTY(RAUMSOLLTEMP_TAG, 0x0005, Type::et_dec_val);
    PROPERTY(RAUMSOLLTEMP_NACHT, 0x0008, Type::et_dec_val);
    PROPERTY(SAMMLERISTTEMP, 0x000d, Type::et_dec_val);
    PROPERTY(VORLAUFISTTEMP, 0x000f, Type::et_dec_val);
    PROPERTY(SPEICHERSOLLTEMP_TAG, 0x0013, Type::et_dec_val);
    PROPERTY(SOLLWERT_MAX_HK1, 0x0028, Type::et_dec_val);
    PROPERTY(SOMMERBETRIEB_TEMP, 0x0116, Type::et_dec_val);
    PROPERTY(SOLLWERT_MIN_HK1, 0x012b, Type::et_dec_val);
    PROPERTY(HYSTERESE_WW, 0x0140, Type::et_dec_val);
    PROPERTY(BETRIEBS_STATUS, 0x0176);
    PROPERTY(FIRMWARE_VERSION, 0x019a, et_cent_val);
    PROPERTY(VOLUMENSTROM, 0x01da, Type::et_dec_val);
    PROPERTY(TAUPUNKT_HK1, 0x0264, Type::et_dec_val);
    PROPERTY(KUEHLMODE, 0x0287, Type::et_bool);
    PROPERTY(PUMPENDREHZAHL_HEIZEN, 0x02cb, Type::et_dec_val);
    PROPERTY(PUMPENDREHZAHL_WW, 0x02cc, Type::et_dec_val);
    PROPERTY(LAUFZEIT_FILTER_TAGE, 0x0341);
    PROPERTY(WAERMEERTRAG_RUECKGE_TAG_WH, 0x03ae);
    PROPERTY(WAERMEERTRAG_RUECKGE_TAG_KWH, 0x03af);
    PROPERTY(WAERMEERTRAG_RUECKGE_SUM_KWH, 0x03b0);
    PROPERTY(WAERMEERTRAG_RUECKGE_SUM_MWH, 0x03b1);
    PROPERTY(RESET_FILTER, 0x033b, Type::et_bool);
    PROPERTY(KUEHL_RAUMSOLL_TAG, 0x0569, Type::et_dec_val);
    PROPERTY(KUEHL_RAUMSOLL_ABWESEND, 0x056a, Type::et_dec_val);
    PROPERTY(KUEHL_RAUMSOLL_NACHT, 0x056b, Type::et_dec_val);
    PROPERTY(LUEFT_STUFE_TAG, 0x056c);
    PROPERTY(LUEFT_STUFE_NACHT, 0x056d);
    PROPERTY(LUEFT_STUFE_BEREITSCHAFT, 0x056f);
    PROPERTY(LUEFT_STUFE_PARTY, 0x0570);
    PROPERTY(PASSIVKUEHLUNG, 0x0575);
    PROPERTY(LUEFT_ZEIT_AUSSERPLAN_STUFE1, 0x0572);
    PROPERTY(LUEFT_ZEIT_AUSSERPLAN_STUFE2, 0x0573);
    PROPERTY(LUEFT_ZEIT_AUSSERPLAN_STUFE3, 0x0574);
    PROPERTY(LUEFT_ZULUFT_STUFE1, 0x0576);
    PROPERTY(LUEFT_ZULUFT_STUFE2, 0x0577);
    PROPERTY(LUEFT_ZULUFT_STUFE3, 0x0578);
    PROPERTY(LUEFT_ABLUFT_STUFE1, 0x0579);
    PROPERTY(LUEFT_ABLUFT_STUFE2, 0x057a);
    PROPERTY(LUEFT_ABLUFT_STUFE3, 0x057b);
    PROPERTY(ANTILEGIONELLEN, 0x0586);
    PROPERTY(WW_TEMP_LEGIONELLEN, 0x0587, Type::et_dec_val);
    PROPERTY(TEMP_FREIGABE_NE, 0x0589, Type::et_dec_val);
    PROPERTY(NE_STUFE_WW, 0x058a);
    PROPERTY(WARMWASSER_ECO, 0x058d, Type::et_bool);
    PROPERTY(ZULUFT_SOLL, 0x0596);
    PROPERTY(ZULUFT_IST, 0x0597);
    PROPERTY(ABLUFT_SOLL, 0x0598);
    PROPERTY(ABLUFT_IST, 0x0599);
    PROPERTY(FORTLUFT_SOLL, 0x059a);
    PROPERTY(FORTLUFT_IST, 0x059b);
    PROPERTY(VERFLUESSIGER_TEMP, 0x059c, Type::et_dec_val);
    PROPERTY(SOMMERBETRIEB_HYSTERESE, 0x05a2, Type::et_dec_val);
    PROPERTY(LAUFZEIT_VERDICHTER_HEIZEN, 0x05a4);
    PROPERTY(LAUFZEIT_VERDICHTER_WW, 0x05a6);
    PROPERTY(LAUFZEIT_NHZ_WW, 0x05a7);
    PROPERTY(LAUFZEIT_NHZ_HEIZEN, 0x05a8);
    PROPERTY(SPEICHERSOLLTEMP_NACHT, 0x05bf, Type::et_dec_val);
    PROPERTY(LUEFT_STUFE_HAND, 0x0612);
    PROPERTY(KUEHLSYSTEM, 0x0613);
    PROPERTY(DRUCK_HEIZKREIS, 0x064a, Type::et_dec_val);
    PROPERTY(WW_LEISTUNG_SOMMER, 0x0690);
    PROPERTY(WW_LEISTUNG_WINTER, 0x0691);
    PROPERTY(LEISTUNG_AUSLEGUNG_KUEHLEN, 0x0692);
    PROPERTY(OLSUMPFTEMPERATUR, 0x0693, Type::et_dec_val);
    PROPERTY(ABLUFTTEMP, 0x0694, Type::et_dec_val);
    PROPERTY(HEIZLEISTUNG_RELATIV, 0x069a, Type::et_double_val);
    PROPERTY(VERDICHTERDREHZAHL, 0x069e);
    PROPERTY(MOTORSTROM, 0x069f);
    PROPERTY(MOTORLEISTUNG, 0x06a0, Type::et_cent_val);
    PROPERTY(MOTORSPANNUNG, 0x06a1);
    PROPERTY(INVERTERTEMPERATUR, 0x06a2, Type::et_dec_val);
    PROPERTY(DRUCK_HOCHDRUCK, 0x07a6, Type::et_cent_val);
    PROPERTY(DRUCK_NIEDERDRUCK, 0x07a7, Type::et_cent_val);
    PROPERTY(WAERMEERTRAG_2WE_WW_TAG_WH, 0x0922);
    PROPERTY(WAERMEERTRAG_2WE_WW_TAG_KWH, 0x0923, Type::et_double_val);
    PROPERTY(WAERMEERTRAG_2WE_WW_SUM_KWH, 0x0924);
    PROPERTY(WAERMEERTRAG_2WE_WW_SUM_MWH, 0x0925, Type::et_double_val);
    PROPERTY(WAERMEERTRAG_2WE_HEIZ_TAG_WH, 0x0926);
    PROPERTY(WAERMEERTRAG_2WE_HEIZ_TAG_KWH, 0x0927, Type::et_double_val);
    PROPERTY(WAERMEERTRAG_2WE_HEIZ_SUM_KWH, 0x0928);
    PROPERTY(WAERMEERTRAG_2WE_HEIZ_SUM_MWH, 0x0929, Type::et_double_val);
    PROPERTY(HEIZ_KUEHL_LEISTUNG, 0xc0ee, Type::et_cent_val);
    PROPERTY(ABLUFTFEUCHTE, 0xc0ef);
    PROPERTY(LEISTUNG_AUSLEGUNG_HEIZUNG, 0xc0f1);
    PROPERTY(VERDICHTER_STARTS, 0xc0f4);
    PROPERTY(VERDICHTER_STARTS_K, 0xc0f5);
    PROPERTY(ABLUFT_TAUPUNKT, 0xc0f6, Type::et_dec_val);
    PROPERTY(LAUFZEIT_FILTER, 0xc111);
    PROPERTY(DIFFERENZDRUCK, 0xc11e);
    PROPERTY(BETRIEBS_STATUS_2, 0xc356);
    PROPERTY(ZEITSPERRE_NE, 0x0588);
#endif

#if defined(THZ_504) || defined(THZ_5_5_ECO)
    PROPERTY(PUMPENZYKLEN_AUSSENTEMP_MIN, 0x05bb);
    PROPERTY(PUMPENZYKLEN_AUSSENTEMP_MAX, 0x05bc);
#endif

#if defined(TTF_07_C)
    PROPERTY(WW_KOMF_TEMP, 0x0013, Type::et_dec_val);
    PROPERTY(WW_HYSTERESE, 0x0022, Type::et_dec_val);
    PROPERTY(PUFFERISTTEMP, 0x0078, Type::et_dec_val);
    PROPERTY(QUELLE_IST, 0x01d4, Type::et_dec_val);
    PROPERTY(PUFFERSOLLTEMP, 0x01d5, Type::et_dec_val);
    PROPERTY(MAXVORLAUFTEMP, 0x01e8, Type::et_dec_val);
    PROPERTY(HKSOLLTEMP, 0x01d7, Type::et_dec_val);
    PROPERTY(HDSENSORMAX, 0x01a2, Type::et_dec_val);
    PROPERTY(QUELLENTEMP_MIN, 0x01b0, Type::et_dec_val);
    PROPERTY(DRUCK_HOCHDRUCK, 0x0268, Type::et_cent_val);
    PROPERTY(HKISTTEMP, 0x02ca, Type::et_dec_val);
    PROPERTY(VOLUMENSTROM, 0x0673, Type::et_cent_val);
    PROPERTY(DRUCK_HEIZKREIS, 0x0674, Type::et_cent_val);
    PROPERTY(QUELLENDRUCK, 0x0675, Type::et_cent_val);
    PROPERTY(VORLAUFISTTEMP, 0x06a1, Type::et_dec_val);
    PROPERTY(KUEHLEN_EINGESCHALTET, 0x06Aa, Type::et_little_bool);
    PROPERTY(LEISTUNG_HEIZKREISPUMPE, 0x070a, Type::et_byte);
    PROPERTY(LEISTUNG_WARMWASSERPUMPE, 0x070b, Type::et_byte);
    PROPERTY(LEISTUNG_SOLEPUMPE, 0x070c, Type::et_byte);
    PROPERTY(EINPHASIGER_BETRIEB, 0x070e, Type::et_bool);
    PROPERTY(VERDICHTER_STARTS, 0x071d);
    PROPERTY(VERDICHTER_STARTS_K, 0x071c);
    PROPERTY(DRUCK_NIEDERDRUCK, 0x07a5, Type::et_cent_val);
    PROPERTY(ANLAGENFROST, 0x0a00, Type::et_dec_val);
    PROPERTY(BETRIEBS_STATUS, 0x0a20, Type::et_default);
    PROPERTY(WW_ECO_TEMP, 0x0a06, Type::et_dec_val);
    PROPERTY(QUELLENMEDIUM, 0xfdae, Type::et_byte);
    PROPERTY(REGLERDYNAMIK, 0xfdb0, Type::et_little_endian);
    PROPERTY(VERDICHTER_STILLSTAND, 0xfdb1, Type::et_little_endian);
#endif

#if defined(THZ_404)
    PROPERTY(PUMPENZYKLEN_MIN_TAG, 0x05b8);
    PROPERTY(PUMPENZYKLEN_MAX_TAG, 0x05b7);
    PROPERTY(PUMPENZYKLEN_AUSSENTEMP_MAX, 0x05b9, Type::et_dec_val);
    PROPERTY(PUMPENZYKLEN_AUSSENTEMP_MIN, 0x05ba, Type::et_dec_val);
    PROPERTY(AKTIVE_HEIZSTUFEN, 0x05bb);
#endif

#if defined(WPL_13) || defined(WPL_17) || defined(WPL_23)
    PROPERTY(RUECKLAUFTEMP, 0x0016, Type::et_dec_val);
    PROPERTY(MAXRUECKLAUFTEMP, 0x0028, Type::et_dec_val);
    PROPERTY(PUFFERISTTEMPERATUR, 0x0078, Type::et_dec_val);
    PROPERTY(BIVALENZTEMPERATUR_HZG, 0x01ac, Type::et_dec_val);
    PROPERTY(PUFFERSOLLTEMPERATUR, 0x01d5, Type::et_dec_val);
    PROPERTY(MAXVORLAUFTEMP, 0x01e8, Type::et_dec_val);
    PROPERTY(EL_NACHERW_ANZ_STUFEN, 0x059f);
    PROPERTY(EL_NACHERW_VERZ_ZEIT, 0x05a0);
    PROPERTY(SPANNUNG_INVERTER, 0x06b1, Type::et_dec_val);
    PROPERTY(STROM_INVERTER, 0x06b2, Type::et_dec_val);
    PROPERTY(STROM_MOTOR, 0x06b4, Type::et_dec_val);
    PROPERTY(VERDICHTER_EINTRITTSTEMP, 0x06d9, Type::et_dec_val);
    PROPERTY(ISTDREHZAHL_VERDICHTER, 0x06eb);
    PROPERTY(SOLLDREHZAHL_VERDICHTER, 0x06ec);
    PROPERTY(DRUCK_HOCHDRUCK, 0x07a6, Type::et_dec_val);
    PROPERTY(DRUCK_NIEDERDRUCK, 0x07a7, Type::et_dec_val);
    PROPERTY(VERDAMPFERTEMP, 0x07a9, Type::et_dec_val);
    PROPERTY(ANLAGEFROST, 0x0a00, Type::et_dec_val);
    PROPERTY(VERFLUESSIGER_TEMP, 0x0a37, Type::et_dec_val);
    PROPERTY(OELSUMPFTEMP, 0x0a39, Type::et_dec_val);
    PROPERTY(UNTERK_COND, 0x0aff, Type::et_dec_val);
    PROPERTY(RAUMEINFLUSS, 0x4ea4);
    PROPERTY(MINTEMP, 0x4ea7, Type::et_dec_val);
    PROPERTY(MAXTEMP, 0x4ea8, Type::et_dec_val);
    PROPERTY(MISCHERDYNAMIK, 0x4ea9);
    PROPERTY(SOLLTEMPERATUR, 0x4eb0, Type::et_dec_val);
    PROPERTY(ISTTEMPERATUR, 0x4eb4, Type::et_dec_val);
    PROPERTY(KOMFORTTEMPERATUR, 0x4eb8, Type::et_dec_val);
    PROPERTY(ECOTEMPERATUR, 0x4eb9, Type::et_dec_val);
    PROPERTY(RAUMISTTEMP, 0x4ec7, Type::et_dec_val);
    PROPERTY(RAUMFEUCHTE, 0x4ec8, Type::et_dec_val);
    PROPERTY(BETRIEBS_STATUS, 0x4ecd);
    PROPERTY(RAUMSOLLTEMP, 0x4ece, Type::et_dec_val);
    PROPERTY(TAUPUNKTTEMP, 0x4ee0, Type::et_dec_val);
    PROPERTY(HYSTERESE_VORLAUFTEMP_KUEHLEN, 0x4f00, Type::et_dec_val);
    PROPERTY(RAUMSOLLTEMP_KUEHLEN, 0x4f04, Type::et_dec_val);
    PROPERTY(ISTTEMPERATUR_KK_2, 0x4f09, Type::et_dec_val);
    PROPERTY(SOLLTEMPERATUR_KK_2, 0x4f0a, Type::et_dec_val);
    PROPERTY(PROGRAMMSCHALTER, 0x4f1b, Type::et_betriebsart);
    PROPERTY(STEIGUNG_HEIZKURVE, 0x4f2b, Type::et_dec_val);
    PROPERTY(VORLAUFISTTEMP_NHZ, 0x4f40, Type::et_dec_val);
    PROPERTY(VORLAUFISTTEMP_WP, 0x4f41, Type::et_dec_val);
    PROPERTY(RUECKLAUFISTTEMP_WP, 0x4f43, Type::et_dec_val);
    PROPERTY(KUEHLEN_ISTTEMP, 0x4f44, Type::et_dec_val);
    PROPERTY(KUEHLEN_SOLLTEMP, 0x4f45, Type::et_dec_val);
    PROPERTY(HEIZUNGSDRUCK, 0x4f46, Type::et_cent_val);
    PROPERTY(VOLUMENSTROM, 0x4f47, Type::et_cent_val);
    PROPERTY(LAUFZEIT_PASSIVKUEHLUNG, 0x4f9a, Type::et_dec_val);
    PROPERTY(ADAPTION_UEBERHITZUNG, 0x4f9e, Type::et_dec_val);
    PROPERTY(SOLL_UEBERHITZUNG_SAUGGAS_VERDICHTER, 0x4fa1, Type::et_dec_val);
    PROPERTY(IST_UEBERHITZUNG_SAUGGAS_VERDICHTER, 0x4fa2, Type::et_dec_val);
    PROPERTY(RUECKLAUFTEMP_QUELLE, 0x4fa6, Type::et_dec_val);
    PROPERTY(VORLAUFTEMP_QUELLE, 0x4fa7, Type::et_dec_val);
    PROPERTY(QUELLENDRUCK, 0x4fa8, Type::et_dec_val);
    PROPERTY(LEISTUNG_QUELLENPUMPE, 0x4fa9, Type::et_dec_val);
    PROPERTY(VERDICHTERDREHZAHLGRENZE, 0x4fac, Type::et_dec_val);
    PROPERTY(STEIGUNG_KUEHLKURVE, 0x4fb9, Type::et_dec_val);
    PROPERTY(STARTTEMPERATUR, 0x4fbe, Type::et_dec_val);
    PROPERTY(HEIZEN_EFFIZIENZ_TAG, 0x501d, Type::et_cent_val);
    PROPERTY(HEIZEN_EFFIZIENZ_JAHR, 0x501e, Type::et_cent_val);
    PROPERTY(LEISTUNG_KUEHLEN, 0x7a40, Type::et_dec_val);
    PROPERTY(UMGEBUNGSTEMPERATUR_INVERTER, 0xc1e6, Type::et_dec_val);
    PROPERTY(TEMPERATUR_INV_VERDICHTER, 0xc1e7, Type::et_dec_val);
    PROPERTY(RUECKLAUFISTTEMP, 0xfdf4, Type::et_dec_val);
    PROPERTY(FROSTSCHUTZ, 0xfe07, Type::et_dec_val);
#endif

#if defined(WPL_13) || defined(WPL_17)
    PROPERTY(VORLAUFTEMP, 0x01d6, Type::et_dec_val);
    PROPERTY(VERDICHTER_STARTS_K, 0x4ef0);
    PROPERTY(VERDICHTER_STARTS, 0x4ef1);
    PROPERTY(ZEITINTERVALL, 0x4f4d, Type::et_dec_val);
    PROPERTY(VORLAUFISTTEMP, 0xfdf3, Type::et_dec_val);
#endif

#if defined(WPL_17) || defined(WPL_23)
    PROPERTY(LAUFZEIT_NHZ1, 0x0259);
    PROPERTY(LAUFZEIT_NHZ2, 0x025a);
    PROPERTY(LAUFZEIT_NHZ1_2, 0x0805);
    PROPERTY(STARTS_ABTAUEN, 0x0806);
    PROPERTY(ZEIT_ABTAUEN, 0x0807);
#endif

#if defined(WPL_13)
    PROPERTY(WAERMEPUMPEN_STATUS, 0x02e2);
#endif

#if defined(WPL_17)
    PROPERTY(WP_WASSERVOLUMENSTROM, 0x02e2, Type::et_dec_val);
    PROPERTY(BIVALENZTEMPERATUR_WW, 0x01ad, Type::et_dec_val);
    PROPERTY(EINSATZGRENZE_HZG, 0x01ae, Type::et_dec_val);
    PROPERTY(EINSATZGRENZE_WW, 0x01af, Type::et_dec_val);
    PROPERTY(AUSSENTEMPERATUR_EINST, 0x01bf, Type::et_dec_val);
    PROPERTY(FESTWERTBETRIEB, 0x01c0, Type::et_dec_val);
    PROPERTY(WW_LERNFUNKTION, 0x027e);
    PROPERTY(REGELABWEICHUNG, 0x033d, Type::et_dec_val);
    PROPERTY(GRENZE_KUEHLEN, 0x03dc, Type::et_dec_val);
    PROPERTY(VORLAUFANTEIL_HEIZKREIS, 0x049d);
    PROPERTY(SENSORABGLEICH_VORLAUF_WP, 0x0658, Type::et_dec_val);
    PROPERTY(SENSORABGLEICH_VORLAUF_NHZ, 0x0659, Type::et_dec_val);
    PROPERTY(SENSORABGLEICH_RUECKLAUF_WP, 0x065a, Type::et_dec_val);
    PROPERTY(AUSLEGUNGSTEMPERATUR, 0x0665, Type::et_dec_val);
    PROPERTY(WAERMEBEDARF, 0x0666, Type::et_dec_val);
    PROPERTY(WW_LEISTUNG_SOMMER, 0x066f);
    PROPERTY(WW_LEISTUNG_WINTER, 0x0670);
    PROPERTY(STANDBY_PUMPENLEISTUNG, 0x067d);
    PROPERTY(SOLLSPREIZUNG, 0x067e, Type::et_dec_val);
    PROPERTY(MAXIMALE_PUMPENLEISTUNG, 0x067f);
    PROPERTY(KONDENSATBEGLEITHEIZUNG_AUSSENTEMPERATUR, 0x0700, Type::et_dec_val);
    PROPERTY(LEISTUNG_WARMWASSERPUMPE, 0x0705);
    PROPERTY(KOMBISPEICHER, 0x070d);
    PROPERTY(EINGANG_X1_13, 0x0713);
    PROPERTY(EINGANG_X1_14, 0x0714);
    PROPERTY(HEIZEN_TEMPERATURVORGABE_1V, 0x0715, Type::et_dec_val);
    PROPERTY(HEIZEN_TEMPERATURVORGABE_10V, 0x0716, Type::et_dec_val);
    PROPERTY(KUEHLEN_TEMPERATURVORGABE_1V, 0x0717, Type::et_dec_val);
    PROPERTY(KUEHLEN_TEMPERATURVORGABE_10V, 0x0718, Type::et_dec_val);
    PROPERTY(FUNKTION_X1_16, 0x0719);
    PROPERTY(PUMPE_X1_16, 0x071a);
    PROPERTY(LEISTUNG_PWM_X1_16, 0x071b);
    PROPERTY(LEISTUNG_VOLT_X1_16, 0x071c, Type::et_dec_val);
    PROPERTY(FUNKTION_X1_17, 0x071d);
    PROPERTY(PUMPE_X1_17, 0x071e);
    PROPERTY(LEISTUNG_PWM_X1_17, 0x071f);
    PROPERTY(LEISTUNG_VOLT_X1_17, 0x0720, Type::et_dec_val);
    PROPERTY(FEHLERAUSGANG, 0x0730);
    PROPERTY(OEFFNUNGSGRAD_EXV, 0x07ca, Type::et_dec_val);
    PROPERTY(SOLL_UEBERHITZUNG, 0x07f3, Type::et_dec_val);
    PROPERTY(IST_UEBERHITZUNG_V, 0x07f4, Type::et_dec_val);
    PROPERTY(VORSTEUER_OEFFNUNGSGRAD_EXV, 0x07f6, Type::et_dec_val);
    PROPERTY(P_FAKTOR, 0x07f7, Type::et_cent_val);
    PROPERTY(I_FAKTOR, 0x07f8, Type::et_cent_val);
    PROPERTY(D_FAKTOR, 0x07f9, Type::et_cent_val);
    PROPERTY(LUEFTERLEISTUNG_REL, 0x0833);
    PROPERTY(FROSTSCHUTZTEMPERATUR, 0x0a36, Type::et_dec_val);
    PROPERTY(REGLERDYNAMIK_HEIZEN, 0x4e8a);
    PROPERTY(SILENT_LEISTUNG, 0x4e9f);
    PROPERTY(SILENT_LUEFTER, 0x4ea0);
    PROPERTY(WAERMEPUMPE_AUS, 0x4ea1);
    PROPERTY(PUFFERTRIEB, 0x4eaf);
    PROPERTY(WW_ANFORDERUNG, 0x4eb2);
    PROPERTY(KONSTANTE_LEISTUNG, 0x4eba, Type::et_dec_val);
    PROPERTY(REDUZIERUNG_LEISTUNG, 0x4ebf);
    PROPERTY(FET_ECO, 0x4ec4);
    PROPERTY(VERDICHTER_SOFORTSTART, 0x4ef4);
    PROPERTY(INBETRIEBNAHME_NOTBETRIEB, 0x4ef5);
    PROPERTY(WW_SOLLTEMPERATUR, 0x4ef9, Type::et_dec_val);
    PROPERTY(EINGESCHALTETE_STUFEN, 0x4efa);
    PROPERTY(LAUFZEIT_VD_HEIZEN, 0x4efb);
    PROPERTY(LAUFZEIT_VD_KUEHLEN, 0x4efc);
    PROPERTY(LAUFZEIT_VD_WW, 0x4efd);
    PROPERTY(KUEHLART, 0x4f05);
    PROPERTY(LAUFZEIT_VD_ABTAUEN, 0x4f06);
    PROPERTY(KUEHLEN, 0x4f07);
    PROPERTY(KUEHLKREIS, 0x4f08);
    PROPERTY(MELDUNGSLISTE, 0x4f0c);
    PROPERTY(SOMMERBETRIEB, 0x4f1e);
    PROPERTY(GEBAEUDEDAEMPFUNG, 0x4f1f);
    PROPERTY(PUMPENZYKLEN, 0x4f21);
    PROPERTY(WARMWASSERBETRIEB, 0x4f24);
    PROPERTY(WARMWASSERHYSTERESE, 0x4f25, Type::et_dec_val);
    PROPERTY(ANTILEGIONELLENBEHANDLUNG, 0x4f28);
    PROPERTY(ABTAUEN_EINLEITEN, 0x4f2d);
    PROPERTY(STILLSTANDSZEIT, 0x4f2e);
    PROPERTY(MINIMALE_ABTAUZEIT, 0x4f2f);
    PROPERTY(MAXIMALER_STROM, 0x4f3f, Type::et_dec_val);
    PROPERTY(AUSSENTEMPERATUR_WP, 0x4f4f, Type::et_dec_val);
    PROPERTY(EVU_SPERRE_CONFIG, 0x4f84);
    PROPERTY(ENTLEERUNG_HYD_2, 0xabe7);
    PROPERTY(ENTLEERUNG_HYD_1, 0xb3bd);
    PROPERTY(RELAIS_NHZ1, 0xb3be);
    PROPERTY(RELAIS_NHZ2, 0xb3bf);
    PROPERTY(RELAIS_NHZ3, 0xb3c0);
    PROPERTY(RELAIS_X_2_3, 0xbb81);
    PROPERTY(RELAIS_X_2_4, 0xbb82);
    PROPERTY(RELAIS_X_2_5, 0xbb83);
    PROPERTY(RELAIS_X_2_6, 0xbb84);
    PROPERTY(RELAIS_X_2_7, 0xbb85);
    PROPERTY(RELAIS_X_2_8, 0xbb86);
    PROPERTY(RELAIS_X_2_9, 0xbb87);
    PROPERTY(RELAIS_X_2_10, 0xbb88);
    PROPERTY(RELAIS_X_2_11, 0xbb89);
    PROPERTY(RELAIS_X_2_12, 0xbb8a);
    PROPERTY(RELAIS_X_2_13, 0xbb8b);
    PROPERTY(RELAIS_X_2_14_1, 0xbb8c);
    PROPERTY(RELAIS_X_2_14_2, 0xbb8d);
    PROPERTY(RELAIS_X_2_15_1, 0xbb8e);
    PROPERTY(RELAIS_X_2_15_2, 0xbb8f);
    PROPERTY(SCHRITTMOTOR_PHASE_1, 0xbb91);
    PROPERTY(SCHRITTMOTOR_PHASE_2, 0xbb93);
    PROPERTY(SCHRITTMOTOR_PHASE_3, 0xbb95);
    PROPERTY(SCHRITTMOTOR_PHASE_4, 0xbb97);
    PROPERTY(KUEHLEN_LEISTUNG, 0xc212, Type::et_dec_val);
    PROPERTY(SOLLDREHZAHL_LUEFTER, 0xc281);
    PROPERTY(ISTDREHZAHL_LUEFTER, 0xc283);
    PROPERTY(TEMPERATUR_INV_LUEFTER, 0xc2c2, Type::et_dec_val);
    PROPERTY(OEFFNUNGSGRAD_BYPASSVENT, 0xc2c3, Type::et_dec_val);
#endif

#if defined(WPL_23)
    PROPERTY(VORLAUFISTTEMP, 0x01d6, Type::et_dec_val);
    PROPERTY(ZWISCHENEINSPRITZUNGSTEMP, 0x05d7, Type::et_dec_val);
    PROPERTY(ZEITINTERVALL, 0x0691, Type::et_dec_val);
    PROPERTY(VERDICHTER_STARTS_K, 0x071c);
    PROPERTY(VERDICHTER_STARTS, 0x071d);
    PROPERTY(REKUPERATORTEMPERATUR, 0x07a3, Type::et_dec_val);
    PROPERTY(LAUFZEIT_VD_HEIZEN, 0x07fc);
    PROPERTY(LAUFZEIT_VD_WW, 0x0802);
    PROPERTY(LAUFZEIT_VD_ABTAUEN, 0x0808);
#endif
};

#endif
