#########################################
#                                       #
#   ESPHome                             #
#                                       #
#########################################
esphome:
  includes:
    - OneESP32ToRuleThemAll/src/callback_handler.h
    - OneESP32ToRuleThemAll/src/communication.h
    - OneESP32ToRuleThemAll/src/mapper.h
    - OneESP32ToRuleThemAll/src/mapper.cpp
    - OneESP32ToRuleThemAll/src/property.h
    - OneESP32ToRuleThemAll/src/property.cpp
    - OneESP32ToRuleThemAll/src/simple_variant.h
    - OneESP32ToRuleThemAll/src/type.h
    - OneESP32ToRuleThemAll/src/type.cpp
    - OneESP32ToRuleThemAll/src/util.h
  platformio_options:
    build_flags:
      - "-std=gnu++2a"
      - "-DESPCLIENT_ID=$espclient_can_id"
      - "-DMANAGER_ID=$manager_can_id"
      - "-DKESSEL_ID=$kessel_can_id"
      - "-DHK1_ID=$hk1_can_id"
      - "-DHK2_ID=$hk2_can_id"
    build_unflags:
      - "-std=gnu++11"
      - "-fno-rtti"

esp32:
  framework:
    advanced:
      loop_task_stack_size: 16384

#########################################
#                                       #
#   Substitutions                       #
#                                       #
#########################################
substitutions:
  interval_very_fast: 15s
  interval_fast: 30s
  interval_medium: 60s
  interval_slow: 5min
  interval_very_slow: 15min
  interval_once_in_a_while: 1h

#########################################
#                                       #
#   Time Synchronization                #
#                                       #
#########################################
time:
  - platform: homeassistant
    id: homeassistant_time
    timezone: $timezone
    on_time:
      - seconds: 0
        minutes: 5
        hours: 3 # sync at 3 am should be ok even with switch from/to daylight saving time
        days_of_week: SUN
        then:
          - lambda: |-
              syncTime();

#########################################
#                                       #
#   Buttons                             #
#                                       #
#########################################
button:
  - platform: template
    name: Synchronize Time
    on_press:
      then:
        - lambda: |-
            syncTime();

#########################################
#                                       #
#   Intervals                           #
#                                       #
#########################################
interval:
  - interval: 250ms
    then:
      - lambda: |-
          // Request sensor value one after another.
          if(!getConditionalRequests().empty()) {
            // find the next request of which the condition evaluates to true
            auto it = std::find_if(getConditionalRequests().begin(),getConditionalRequests().end(),[](const auto& element){
              return element._condition();
            });
            if(it != getConditionalRequests().end()) {
              requestData(it->_task.first, it->_task.second);
              getConditionalRequests().erase(it);
            }
          }
  - interval: 50ms
    then:
      - lambda: |-
          // Request sensor value one after another.
          if(!getConditionalTransmissions().empty()) {
            // find the next request of which the condition evaluates to true
            auto it = std::find_if(getConditionalTransmissions().begin(),getConditionalTransmissions().end(),[](const auto& element){
              return element._condition();
            });
            if(it != getConditionalTransmissions().end()) {
              sendData(it->_task.first, it->_task.second, it->_value);
              getConditionalTransmissions().erase(it);
            }
          }

#########################################
#                                       #
#   CANbus configuration                #
#                                       #
#########################################
canbus:
  - id: wp_can
    can_id: $espclient_can_id
    use_extended_id: false
    on_frame:
    - can_id: 0
      can_id_mask: 0
      then:
        - lambda: |-
            ESP_LOGD("CAN", "Can message received with CANId 0x%04lx", can_id);
            const auto [property, value] = processCanMessage(x);
            const auto canMember = getCanMemberByCanId(can_id);
            if(canMember) {
              auto callback = CallbackHandler::instance().getCallback(std::make_pair(canMember->get(),property));
              callback(value);
            } else {
              ESP_LOGD("CAN", "No CANMember with CANId 0x%04lx available.", can_id);
            }

#########################################
#                                       #
#   Home Assistant Actions              #
#                                       #
#########################################
api:
  actions:
    - action: can_send_raw_data
      variables:
        data: int[]
      then:
        - lambda: |-
            if(data.size() != 7U) {
              ESP_LOGE("ACTION", "Data is expected to have 7 elements, but has %zd .", data.size());
              return;
            }
            ESP_LOGI("ACTION", "Sending data (0x%02x 0x%02x 0x%02x 0x%02x 0x%02x 0x%02x 0x%02x)", data[0], data[1], data[2], data[3], data[4], data[5], data[6]);
            const auto use_extended_id{false};
            std::vector<std::uint8_t> payload;
            payload.resize(data.size());
            std::transform(data.begin(),data.end(),payload.begin(),[](const auto in){ return static_cast<std::uint8_t>(in);});
            id(wp_can).send_data(ESPClient.canId, use_extended_id, payload);
    - action: can_send_value
      variables:
        property: int
        target: string
        raw_value: int
      then:
        - lambda: |-
            Property mappedProperty(static_cast<std::uint16_t>(property));
            const auto value{static_cast<std::uint16_t>(raw_value)};
            if(const auto member = getCanMemberByName(target); member.has_value()) {
              ESP_LOGI("ACTION", "Sending value %d for property %s (0x%04x) to %s", value, std::string(mappedProperty.name).c_str(), mappedProperty.id, target.c_str());
              queueTransmission(member.value(), mappedProperty, value);
            } else {
              ESP_LOGI("ACTION","No CanMember with name %s defined!", target.c_str());
            }

#########################################
#                                       #
#   Scripts                             #
#                                       #
#########################################
script:
  - id: mqtt_push_event
    mode: queued
    parameters:
      suffix: string
      payload: string
    then:
