#########################################
#                                       #
#   Kondensatpumpe Störung              #
#                                       #
#########################################
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO16
      mode:
        input: true
        pullup: true
    device_class: problem
    name: "Kondensatpumpe Störung"
    filters:
      - delayed_on: 1s
      - delayed_off: 1min
