one_wire:
  - platform: gpio
    id: bus_ug_eg
    pin: GPIO1

  - platform: gpio
    id: bus_og
    pin: GPIO3

sensor:
  - platform: dallas_temp
    one_wire_id: bus_ug_eg
    address: 0x18000000b9f5e328
    name: "Gäste Badezimmer Rücklauf Temperatur"
    id: gaeste_badezimmer_ruecklauf_temperatur
    device_class: temperature
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    icon: mdi:thermometer
    update_interval: 5min

  - platform: dallas_temp
    one_wire_id: bus_ug_eg
    address: 0xc6000000b1f07b28
    name: "Flur EG Rücklauf Temperatur"
    id: flur_eg_ruecklauf_temperatur
    device_class: temperature
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    icon: mdi:thermometer
    update_interval: 5min

  - platform: dallas_temp
    one_wire_id: bus_ug_eg
    address: 0x96000000b379fc28
    name: "Büro Rücklauf Temperatur"
    id: buero_ruecklauf_temperatur
    device_class: temperature
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    icon: mdi:thermometer
    update_interval: 5min

  - platform: dallas_temp
    one_wire_id: bus_ug_eg
    address: 0x66000000b3c2f628
    name: "Esszimmer Rücklauf Temperatur"
    id: esszimmer_ruecklauf_temperatur
    device_class: temperature
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    icon: mdi:thermometer
    update_interval: 5min

  - platform: dallas_temp
    one_wire_id: bus_ug_eg
    address: 0x31000000b1f3a728
    name: "Küche Rücklauf Temperatur"
    id: kueche_ruecklauf_temperatur
    device_class: temperature
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    icon: mdi:thermometer
    update_interval: 5min

  - platform: dallas_temp
    one_wire_id: bus_ug_eg
    address: 0x59000000b3c08928
    name: "Wohnzimmer Rücklauf Temperatur 1"
    id: wohnzimmer_ruecklauf_temperatur_1
    device_class: temperature
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    icon: mdi:thermometer
    update_interval: 5min

  - platform: dallas_temp
    one_wire_id: bus_ug_eg
    address: 0x33000000b9f06d28
    name: "Wohnzimmer Rücklauf Temperatur 2"
    id: wohnzimmer_ruecklauf_temperatur_2
    device_class: temperature
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    icon: mdi:thermometer
    update_interval: 5min

  - platform: dallas_temp
    one_wire_id: bus_ug_eg
    address: 0xdc000000b3933a28
    name: "Sauna Rücklauf Temperatur 1"
    id: sauna_ruecklauf_temperatur_1
    device_class: temperature
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    icon: mdi:thermometer
    update_interval: 5min

  - platform: dallas_temp
    one_wire_id: bus_ug_eg
    address: 0x11000000b3fda028
    name: "Sauna Rücklauf Temperatur 2"
    id: sauna_ruecklauf_temperatur_2
    device_class: temperature
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    icon: mdi:thermometer
    update_interval: 5min

  - platform: dallas_temp
    one_wire_id: bus_ug_eg
    address: 0xe6000000b9ed9c28
    name: "Flur UG Rücklauf Temperatur"
    id: flur_ug_ruecklauf_temperatur
    device_class: temperature
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    icon: mdi:thermometer
    update_interval: 5min

  - platform: dallas_temp
    one_wire_id: bus_ug_eg
    address: 0xbc000000b3893228
    name: "Kaltwasser Temperatur"
    id: kaltwasser_temperatur
    device_class: temperature
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    icon: mdi:thermometer
    update_interval: 5min

  - platform: dallas_temp
    one_wire_id: bus_og
    address: 0x8e000000b1fa9f28
    name: "Kinder Badezimmer Rücklauf Temperatur"
    id: kinder_badezimmer_ruecklauf_temperatur
    device_class: temperature
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    icon: mdi:thermometer
    update_interval: 5min

  - platform: dallas_temp
    one_wire_id: bus_og
    address: 0x12000000b3c32a28
    name: "Flur OG Rücklauf Temperatur"
    id: flur_og_ruecklauf_temperatur
    device_class: temperature
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    icon: mdi:thermometer
    update_interval: 5min

  - platform: dallas_temp
    one_wire_id: bus_og
    address: 0xde000000b9f52028
    name: "Julia Rücklauf Temperatur 1"
    id: julia_ruecklauf_temperatur_1
    device_class: temperature
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    icon: mdi:thermometer
    update_interval: 5min

  - platform: dallas_temp
    one_wire_id: bus_og
    address: 0x78000000b3cc8928
    name: "Julia Rücklauf Temperatur 2"
    id: julia_ruecklauf_temperatur_2
    device_class: temperature
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    icon: mdi:thermometer
    update_interval: 5min

  - platform: dallas_temp
    one_wire_id: bus_og
    address: 0xd3000000b1b71928
    name: "Nora Rücklauf Temperatur"
    id: nora_ruecklauf_temperatur
    device_class: temperature
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    icon: mdi:thermometer
    update_interval: 5min

  - platform: dallas_temp
    one_wire_id: bus_og
    address: 0xc0000000ba02de28
    name: "Schlafzimmer Rücklauf Temperatur"
    id: schlafzimmer_ruecklauf_temperatur
    device_class: temperature
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    icon: mdi:thermometer
    update_interval: 5min

  - platform: dallas_temp
    one_wire_id: bus_og
    address: 0x40000000b3a0c528
    name: "Badezimmer Rücklauf Temperatur 1"
    id: badezimmer_ruecklauf_temperatur_1
    device_class: temperature
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    icon: mdi:thermometer
    update_interval: 5min

  - platform: dallas_temp
    one_wire_id: bus_og
    address: 0x40000000b3bbaf28
    name: "Badezimmer Rücklauf Temperatur 2"
    id: badezimmer_ruecklauf_temperatur_2
    device_class: temperature
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    icon: mdi:thermometer
    update_interval: 5min

# 20 0xc6000000ba0a2328
