#########################################
#                                       #
#   Wassermelder                        #
#                                       #
#########################################
binary_sensor:
  - platform: gpio
    pin: 
      number: GPIO1
      mode:
        input: true
        pullup: true
      inverted: true
    filters:
      - delayed_on_off: 1s
    name: "Wassermelder 2"
