esphome:
  platformio_options:
    build_flags:
      - "-DTHZ_404"

packages:
  COMMON: !include { file: common.yaml }
  BASE:   !include { file: wp_base.yaml }

  SOMMERBETRIEB_HYSTERESE:    !include { file: wp_temperature.yaml, vars: { property: "SOMMERBETRIEB_HYSTERESE", update_interval: $interval_slow }}
  HEISSGAS_TEMP:              !include { file: wp_temperature.yaml, vars: { property: "HEISSGAS_TEMP"          , update_interval: $interval_slow }}
  VERFLUESSIGER_TEMP:         !include { file: wp_temperature.yaml, vars: { property: "VERFLUESSIGER_TEMP"     , update_interval: $interval_slow }}
  PUMPENZYKLEN_MAX_AUSSENT:   !include { file: wp_temperature.yaml, vars: { property: "PUMPENZYKLEN_MAX_AUSSENT" }}
  
  PUMPENZYKLEN_MIN_TAG:       !include { file: wp_generic.yaml, vars: { property: "PUMPENZYKLEN_MIN_TAG" , icon: "mdi:numeric", update_interval: $interval_very_slow  }}
  PUMPENZYKLEN_MAX_TAG:       !include { file: wp_generic.yaml, vars: { property: "PUMPENZYKLEN_MAX_TAG" , icon: "mdi:numeric", update_interval: $interval_very_slow  }}
  LAUFZEIT_FILTER_TAGE:       !include { file: wp_generic.yaml,     vars: { property: "LAUFZEIT_FILTER_TAGE"      , icon: "mdi:air-filter"       , update_interval: $interval_once_in_a_while, unit: "d" }}
  DRUCK_HEIZKREIS:            !include { file: wp_generic.yaml,     vars: { property: "DRUCK_HEIZKREIS"           , icon: "mdi:gauge"            , update_interval: $interval_medium, unit: "bar", accuracy_decimals: "1" }}
  AKTIVE_HEIZSTUFEN:          !include { file: wp_generic.yaml,     vars: { property: "AKTIVE_HEIZSTUFEN"         , icon: "mdi:heat-pump-outline", update_interval: $interval_medium}}
  LAUFZEIT_VERDICHTER_HEIZEN: !include { file: wp_generic.yaml,     vars: { property: "LAUFZEIT_VERDICHTER_HEIZEN", icon: "mdi:calendar-clock"   , update_interval: $interval_slow }}
  LAUFZEIT_VERDICHTER_WW:     !include { file: wp_generic.yaml,     vars: { property: "LAUFZEIT_VERDICHTER_WW"    , icon: "mdi:calendar-clock"   , update_interval: $interval_slow }}
  LAUFZEIT_NHZ_HEIZEN:        !include { file: wp_generic.yaml,     vars: { property: "LAUFZEIT_NHZ_HEIZEN"       , icon: "mdi:calendar-clock"   , update_interval: $interval_slow }}
  LAUFZEIT_NHZ_WW:            !include { file: wp_generic.yaml,     vars: { property: "LAUFZEIT_NHZ_WW"           , icon: "mdi:calendar-clock"   , update_interval: $interval_slow }}

  SOMMERBETRIEB_TEMP:         !include { file: wp_number.yaml,      vars: { property: "SOMMERBETRIEB_TEMP", icon: "mdi:sun-thermometer", min: "10.0", max: "20.0", step: "1.0", unit: "°C"}}

binary_sensor:
  - platform: template
    name: "SOMMERMODUS"
    id: SOMMERMODUS
    trigger_on_initial_state: false
    lambda: |-
      if (id(AUSSENTEMP).state >= (id(SOMMERBETRIEB_TEMP).state + id(SOMMERBETRIEB_HYSTERESE).state)) {
        id(SOMMERMODUS).publish_state(true);
      } else if (id(AUSSENTEMP).state <= (id(SOMMERBETRIEB_TEMP).state - id(SOMMERBETRIEB_HYSTERESE).state)) {
        id(SOMMERMODUS).publish_state(false);
      } else {
        id(SOMMERMODUS).publish_state(id(SOMMERMODUS).state);
      }
      return {};

sensor:
  - platform: template
    name: "HEIZKREIS_DIFF"
    id: HEIZKREIS_DIFF
    icon: "mdi:swap-vertical"
    state_class: "measurement"
    accuracy_decimals: 1
    lambda: |-
      id(HEIZKREIS_DIFF).publish_state(id(RUECKLAUFISTTEMP).state - id(VORLAUFSOLLTEMP).state);
      return {};
