esphome:
  platformio_options:
    build_flags:
      - "-DTHZ_5_5_ECO"

packages:
  COMMON: !include { file: common.yaml }
  BASE:   !include { file: wp_base.yaml }

  ZEITSPERRE_NE:            !include { file: wp_number.yaml , vars: { property: "ZEITSPERRE_NE" , icon: "mdi:valve" , min: "0", max: "360", step: "5.0" }}
