#########################################
#                                       #
#   ESPHome                             #
#                                       #
#########################################
esphome:
  platformio_options:
    build_flags:
      - "-DTHZ_504"

#########################################
#                                       #
#   Global variables                    #
#                                       #
#########################################
globals:
  - id: heat_pump_variant
    type: std::string
    initial_value: '"THZ504"'

#########################################
#                                       #
#   Packages                            #
#                                       #
#########################################
packages:
  THZ_BASE:        !include { file: thz_base.yaml }

  ABLUFT_TAUPUNKT: !include { file: templates/wp_temperature.yaml, vars: { property: "ABLUFT_TAUPUNKT" }}

  DIFFERENZDRUCK:              !include { file: templates/wp_generic.yaml, vars: { property: "DIFFERENZDRUCK"              , update_interval: $interval_medium, unit: "Pa", icon: "mdi:air-filter"}}
  LAUFZEIT_VERDICHTER_KUEHLEN: !include { file: templates/wp_generic.yaml, vars: { property: "LAUFZEIT_VERDICHTER_KUEHLEN" , update_interval: $interval_slow  , unit: "h" , icon: "mdi:timer-sand-complete", state_class: "total_increasing" }}
