#########################################
#                                       #
#   ESPHome                             #
#                                       #
#########################################
esphome:
  platformio_options:
    build_flags:
      - "-DTHZ_504"

#########################################
#                                       #
#   Packages                            #
#                                       #
#########################################
packages:
  THZ_BASE:        !include { file: thz_base.yaml }

  ABLUFT_TAUPUNKT: !include { file: templates/wp_temperature.yaml, vars: { property: "ABLUFT_TAUPUNKT" }}

  DIFFERENZDRUCK:  !include { file: templates/wp_generic.yaml, vars: { property: "DIFFERENZDRUCK" , icon: "mdi:air-filter", unit: "Pa", update_interval: $interval_medium }}
