#########################################
#                                       #
#   ESPHome                             #
#                                       #
#########################################
esphome:
  platformio_options:
    build_flags:
      - "-DTHZ_5_5_ECO"

#########################################
#                                       #
#   Global variables                    #
#                                       #
#########################################
globals:
  - id: heat_pump_variant
    type: std::string
    initial_value: '"THZ55ECO"'

#########################################
#                                       #
#   Packages                            #
#                                       #
#########################################
packages:
  THZ_BASE:      !include { file: thz_base.yaml }

  ZEITSPERRE_NE: !include { file: templates/wp_number.yaml , vars: { property: "ZEITSPERRE_NE" , icon: "mdi:valve" , min: "0", max: "360", step: "5.0" }}
