defaults:
  target: "Kessel"
  internal: "false"
  disabled_by_default: "false"

sensor:
  - platform: template
    name: ${property}
    id: ${property}
    unit_of_measurement: ${unit}
    icon: "mdi:heating-coil"
    state_class: measurement
    internal: ${internal}
    disabled_by_default: ${disabled_by_default}
    accuracy_decimals: 0
    update_interval: $interval_once_in_a_while
    filters:
        - throttle: $interval_once_in_a_while
    lambda: |-
        queueRequest(${target}, Property::k${property});
        return {};

esphome:
  on_boot:
    priority: -100
    then:
      - lambda: |-
          CallbackHandler::instance().addCallback(std::make_pair(${target},Property::k${property}),[](const SimpleVariant& value){
              id(${property}).publish_state(value);
          });
          queueRequest(${target}, Property::k${property});
