defaults:
  icon: "mdi:blank"
  accuracy_decimals: "0"
  target: "Kessel"
  update_interval: "never"
  unit: ""
  scaler: "1.0"
  name_suffix: ""

sensor:
  - platform: template
    name: ${property}${name_suffix}
    id: ${property}${name_suffix}
    icon: ${icon}
    unit_of_measurement: ${unit}
    accuracy_decimals: ${accuracy_decimals}
    update_interval: ${update_interval}
    state_class: "measurement"
    lambda: |-
        queueRequest(${target}, Property::k${property});
        return {};

esphome:
  on_boot:
    priority: -100
    then:
      - lambda: |-
          CallbackHandler::instance().addCallback(std::make_pair(${target},Property::k${property}),[](const SimpleVariant& value){
              id(${property}${name_suffix}).publish_state(${scaler} * value.get<float>());
          });
          queueRequest(${target}, Property::k${property});
