defaults:
  target: "Kessel"
  step: "1"
  min: "0"
  max: "100"

number:
  - platform: template
    name: ${property}
    id: ${property}
    icon: "mdi:valve"
    min_value: ${min}
    max_value: ${max}
    step: ${step}
    initial_value: NAN
    optimistic: true
    set_action:
      - lambda: |-
          ESP_LOGI("Number", "Setting new value %f for %s", x, std::string(Property::k${property}.name).c_str());
          if(x != NAN) {
            const auto type = Property::k${property}.type;
            switch(type) {
              case Type::et_little_endian: {
                  const auto value{static_cast<std::uint16_t>(x)};
                  const auto raw_value = static_cast<std::uint16_t>((((value >> 8U) & 0xFF) | ((value & 0xff) << 8U)));
                  sendData(${target}, Property::k${property}, raw_value);
                  break;
                }
              default:
                sendData(${target}, Property::k${property}, static_cast<std::uint16_t>(round(x / ${step})));
                break;
            }
          }

esphome:
  on_boot:
    priority: -100
    then:
      - lambda: |-
          CallbackHandler::instance().addCallbacks({std::make_pair(${target},Property::k${property}),
                                                    std::make_pair(Manager,Property::k${property})},[](const SimpleVariant& value){
              id(${property}).publish_state(value);
          });
          queueRequest(${target}, Property::k${property});
