defaults:
  update_interval: $interval_very_slow
  target: "Kessel"

sensor:
  - platform: template
    name: ${property}
    id: ${property}
    unit_of_measurement: "°C"
    icon: "mdi:thermometer-lines"
    device_class: "temperature"
    state_class: "measurement"
    accuracy_decimals: 1
    update_interval: ${update_interval}
    lambda: |-
        queueRequest(${target}, Property::k${property});
        return {};

esphome:
  on_boot:
    priority: -100
    then:
      - lambda: |-
          CallbackHandler::instance().addCallback(std::make_pair(${target},Property::k${property}),[](const SimpleVariant& value){
              id(${property}).publish_state(value);
          });
          queueRequest(${target}, Property::k${property});
