#########################################
#                                       #
#   ESPHome                             #
#                                       #
#########################################
esphome:
  platformio_options:
    build_flags:
      - "-DWPL_13"
  on_boot:
    priority: 100.0
    then:
      - lambda: |-
          CallbackHandler::instance().addCallback(std::make_pair(Manager,Property::kWAERMEPUMPEN_STATUS),[](const SimpleVariant& value){
            const std::bitset<9U> status_bits{static_cast<std::uint16_t>(value)};
            id(VERDICHTER).publish_state(status_bits.test(0U));
            id(OELSUMPFHEIZUNG).publish_state(status_bits.test(1U));
            id(SICHERHEITSKETTE).publish_state(status_bits.test(2U));
            id(NETZVERSORGUNG_INVERTER).publish_state(status_bits.test(3U));
            id(STOERUNG).publish_state(status_bits.test(4U));
            id(SOLEDRUCK_WAECHTER).publish_state(status_bits.test(5U));
            id(WAERMEQUELLENPUMPE).publish_state(status_bits.test(6U));
            id(PASSIVKUEHLVENTIL_HEIZEN).publish_state(status_bits.test(7U));
            id(PASSIVKUEHLVENTIL_KUEHLEN).publish_state(status_bits.test(8U));
          });
          queueRequest(Manager, Property::kWAERMEPUMPEN_STATUS);

#########################################
#                                       #
#   Substitutions                       #
#                                       #
#########################################
substitutions:
  kessel_can_id: "0x180"
  hk1_can_id: "0x601"
  hk2_can_id: "0x602"
  manager_can_id: "0x514"
  espclient_can_id: "0x6a2"

#########################################
#                                       #
#   Global variables                    #
#                                       #
#########################################
globals:
  - id: heat_pump_variant
    type: std::string
    initial_value: '"WPL13"'

#########################################
#                                       #
#   Packages                            #
#                                       #
#########################################

packages:
  wpl_base:                             !include { file: wpl_base.yaml }

  VERDICHTER:                           !include { file: templates/wp_binary.yaml, vars: { name: "VERDICHTER" }}
  OELSUMPFHEIZUNG:                      !include { file: templates/wp_binary.yaml, vars: { name: "OELSUMPFHEIZUNG" }}
  SICHERHEITSKETTE:                     !include { file: templates/wp_binary.yaml, vars: { name: "SICHERHEITSKETTE" }}
  NETZVERSORGUNG_INVERTER:              !include { file: templates/wp_binary.yaml, vars: { name: "NETZVERSORGUNG_INVERTER" }}
  STOERUNG:                             !include { file: templates/wp_binary.yaml, vars: { name: "STOERUNG" }}
  SOLEDRUCK_WAECHTER:                   !include { file: templates/wp_binary.yaml, vars: { name: "SOLEDRUCK_WAECHTER" }}
  WAERMEQUELLENPUMPE:                   !include { file: templates/wp_binary.yaml, vars: { name: "WAERMEQUELLENPUMPE" }}
  PASSIVKUEHLVENTIL_HEIZEN:             !include { file: templates/wp_binary.yaml, vars: { name: "PASSIVKUEHLVENTIL_HEIZEN" }}
  PASSIVKUEHLVENTIL_KUEHLEN:            !include { file: templates/wp_binary.yaml, vars: { name: "PASSIVKUEHLVENTIL_KUEHLEN" }}
